name: CI

on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '10', '8' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: npm ci
    - name: Project Tests
      run: npm test

  test_latest:
    name: Test on latest Node
    runs-on: ubuntu-latest
    container: node:current
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm ci
    - name: Project Tests
      run: npm test

  eslint:
    name: Check ESLint
    runs-on: ubuntu-latest
    container: node:current
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm ci
    - name: check lint
      run: npm run lint
